export const mysql5 = [
  {
    index: 1,
    question: "What is the primary purpose of Spring Data?",
    choices: [
      "To create web applications",
      "To simplify data access and persistence",
      "To manage transactions",
      "To provide an ORM framework",
    ],
    correctAnswer: "To simplify data access and persistence",
    imageURL: null,
  },
  {
    index: 2,
    question: "Which of the following modules is part of Spring Data?",
    choices: [
      "Spring Data JPA",
      "Spring Data MVC",
      "Spring Data REST",
      "Spring Data Security",
    ],
    correctAnswer: "Spring Data JPA",
    imageURL: null,
  },
  {
    index: 3,
    question: "What is a Repository in Spring Data?",
    choices: [
      "A service for database connections",
      "An interface for CRUD operations",
      "A configuration class for Hibernate",
      "A data source",
    ],
    correctAnswer: "An interface for CRUD operations",
    imageURL: null,
  },
  {
    index: 4,
    question: "Which annotation is used to indicate a Spring Data repository interface?",
    choices: [
      "@Repository",
      "@Service",
      "@Component",
      "@Entity",
    ],
    correctAnswer: "@Repository",
    imageURL: null,
  },
  {
    index: 5,
    question: "How does Spring Data JPA simplify the implementation of data access layers?",
    choices: [
      "By using SQL directly",
      "By generating SQL queries from method names",
      "By enforcing a strict schema",
      "By eliminating the need for configuration",
    ],
    correctAnswer: "By generating SQL queries from method names",
    imageURL: null,
  },
  {
    index: 6,
    question: "Which interface does Spring Data JPA provide for basic CRUD operations?",
    choices: [
      "JpaRepository",
      "CrudRepository",
      "Repository",
      "EntityRepository",
    ],
    correctAnswer: "JpaRepository",
    imageURL: null,
  },
  {
    index: 7,
    question: "What is the role of the `@EnableJpaRepositories` annotation?",
    choices: [
      "To enable JPA repositories in the Spring application",
      "To configure database connections",
      "To create entity classes",
      "To handle transactions",
    ],
    correctAnswer: "To enable JPA repositories in the Spring application",
    imageURL: null,
  },
  {
    index: 8,
    question: "What type of queries can you create using Spring Data Query Methods?",
    choices: [
      "Dynamic SQL queries",
      "JPQL queries",
      "Both A and B",
      "No queries are allowed",
    ],
    correctAnswer: "Both A and B",
    imageURL: null,
  },
  {
    index: 9,
    question: "Which annotation is used to specify a custom query in Spring Data JPA?",
    choices: [
      "@Query",
      "@Select",
      "@CustomQuery",
      "@NamedQuery",
    ],
    correctAnswer: "@Query",
    imageURL: null,
  },
  {
    index: 10,
    question: "What is the benefit of using Spring Data REST?",
    choices: [
      "Automatic RESTful API creation from repositories",
      "Improved database performance",
      "Simplified entity relationships",
      "Support for multiple database engines",
    ],
    correctAnswer: "Automatic RESTful API creation from repositories",
    imageURL: null,
  },

];