export const mysql4 = [
  {
    index: 1,
    question: "What does 'Code First' mean in the context of Hibernate?",
    choices: [
      "Creating database tables before coding",
      "Generating database schema from code",
      "Writing SQL code first",
      "Mapping database tables to code manually",
    ],
    correctAnswer: "Generating database schema from code",
    imageURL: null,
  },
  {
    index: 2,
    question: "Which annotation is used to specify the primary key in a Code First entity?",
    choices: [
      "@Id",
      "@PrimaryKey",
      "@Key",
      "@EntityKey",
    ],
    correctAnswer: "@Id",
    imageURL: null,
  },
  {
    index: 3,
    question: "In a Code First approach, which Hibernate annotation is used to define a one-to-many relationship?",
    choices: [
      "@ManyToOne",
      "@OneToMany",
      "@OneToOne",
      "@ManyToMany",
    ],
    correctAnswer: "@OneToMany",
    imageURL: null,
  },
  {
    index: 4,
    question: "What is the purpose of the `@GeneratedValue` annotation in Hibernate?",
    choices: [
      "To auto-generate primary key values",
      "To specify the database table name",
      "To enforce unique constraints",
      "To manage transactions",
    ],
    correctAnswer: "To auto-generate primary key values",
    imageURL: null,
  },
  {
    index: 5,
    question: "Which class is typically used to create a Hibernate `SessionFactory` in a Code First approach?",
    choices: [
      "Configuration",
      "Session",
      "EntityManager",
      "Factory",
    ],
    correctAnswer: "Configuration",
    imageURL: null,
  },
  {
    index: 6,
    question: "What method is used to update an existing entity in Hibernate Code First?",
    choices: [
      "save()",
      "update()",
      "merge()",
      "persist()",
    ],
    correctAnswer: "update()",
    imageURL: null,
  },
  {
    index: 7,
    question: "How do you specify a unique constraint on an entity field in Hibernate Code First?",
    choices: [
      "@Unique",
      "@Column(unique = true)",
      "@Id",
      "@Constraint",
    ],
    correctAnswer: "@Column(unique = true)",
    imageURL: null,
  },
  {
    index: 8,
    question: "In a Code First approach, which method is used to delete an entity?",
    choices: [
      "remove()",
      "delete()",
      "destroy()",
      "erase()",
    ],
    correctAnswer: "remove()",
    imageURL: null,
  },
  {
    index: 9,
    question: "Which annotation is used to specify a many-to-many relationship in Hibernate Code First?",
    choices: [
      "@ManyToMany",
      "@OneToMany",
      "@ManyToOne",
      "@Relationship",
    ],
    correctAnswer: "@ManyToMany",
    imageURL: null,
  },
  {
    index: 10,
    question: "What is the role of the `@Table` annotation in a Hibernate Code First entity?",
    choices: [
      "To define the entity's primary key",
      "To specify the database table name",
      "To map relationships",
      "To configure entity caching",
    ],
    correctAnswer: "To specify the database table name",
    imageURL: null,
  },

];