export const mysql8 = [
  {
    index: 1,
    question: "What does JSON stand for?",
    choices: [
      "JavaScript Object Notation",
      "Java Standard Object Notation",
      "JavaScript Online Notation",
      "Java Structured Object Notation",
    ],
    correctAnswer: "JavaScript Object Notation",
    imageURL: null,
  },
  {
    index: 2,
    question: "Which of the following is a valid JSON format?",
    choices: [
      "{name: 'John', age: 30}",
      '{"name": "John", "age": 30}',
      "[name: 'John', age: 30]",
      "['name': 'John', 'age': 30]",
    ],
    correctAnswer: '{"name": "John", "age": 30}',
    imageURL: null,
  },
  {
    index: 3,
    question: "What is the main use of JSON?",
    choices: [
      "Data storage",
      "Data interchange between a server and a web application",
      "Database management",
      "Data encryption",
    ],
    correctAnswer: "Data interchange between a server and a web application",
    imageURL: null,
  },
  {
    index: 4,
    question: "Which of the following is NOT a valid JSON data type?",
    choices: [
      "String",
      "Number",
      "Object",
      "Function",
    ],
    correctAnswer: "Function",
    imageURL: null,
  },
  {
    index: 5,
    question: "How do you parse a JSON string in JavaScript?",
    choices: [
      "JSON.parse()",
      "JSON.stringify()",
      "JSON.decode()",
      "JSON.load()",
    ],
    correctAnswer: "JSON.parse()",
    imageURL: null,
  },
  {
    index: 6,
    question: "Which method converts a JavaScript object into a JSON string?",
    choices: [
      "JSON.parse()",
      "JSON.stringify()",
      "JSON.toString()",
      "JSON.convert()",
    ],
    correctAnswer: "JSON.stringify()",
    imageURL: null,
  },
  {
    index: 7,
    question: "In JSON, what character is used to denote an array?",
    choices: [
      "{}",
      "[]",
      "()",
      "<>",
    ],
    correctAnswer: "[]",
    imageURL: null,
  },
  {
    index: 8,
    question: "What is the purpose of the `JSON Schema`?",
    choices: [
      "To define the structure of JSON data",
      "To encrypt JSON data",
      "To compress JSON data",
      "To convert JSON to XML",
    ],
    correctAnswer: "To define the structure of JSON data",
    imageURL: null,
  },
  {
    index: 9,
    question: "Which library can be used in Java to process JSON?",
    choices: [
      "Jackson",
      "Spring",
      "Hibernate",
      "JDBC",
    ],
    correctAnswer: "Jackson",
    imageURL: null,
  },
  {
    index: 10,
    question: "What is the output of the following JavaScript code: `console.log(JSON.stringify({ name: 'Alice', age: 25 }));`?",
    choices: [
      "{ name: 'Alice', age: 25 }",
      "{\"name\":\"Alice\",\"age\":25}",
      "['Alice', 25]",
      "[name: 'Alice', age: 25]",
    ],
    correctAnswer: "{\"name\":\"Alice\",\"age\":25}",
    imageURL: null,
  },

];